[package]
name = "hacspecs"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
hacspec = "0.1"
wrapping_arithmetic = "0.1"
contracts = "0.3"
paste = "0.1"
uint = { git = "https://github.com/franziskuskiefer/rust-uint-n" }
# uint = { path = "../rust-uint-n" }

[patch.crates-io]
# wrapping_arithmetic = { git = "https://github.com/franziskuskiefer/wrapping-arithmetic" }
hacspec = { git = "https://github.com/hacspec/hacspec-rust" }
# hacspec = { path = "../hacspec-rust" }
