[package]
name = "hacspecs"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
num = "0.2"
# hacspec = { git = "https://github.com/hacspec/hacspec-rust", branch="denismerigoux_formalization" }
hacspec = { path = "../hacspec-rust" }
contracts = "0.3"
paste = "0.1"

secret_integers = "0.1.5"
abstract_integers = { git = "https://github.com/denismerigoux/rust-abstract-integers" }
# abstract_integers = { path = "../rust-abstract-integers" }
